
# generated by calling "grep train log.txt > train.txt" on the log file 
# for a run
inDir <- "/mnt/data2/BaderLab/PanCancer_LUSC/output/integrate_170203";

# get training information from log
system(sprintf("grep train %s/log.txt > %s/train.txt",inDir,inDir))
inFile <- sprintf("%s/train.txt",inDir)

dat <- read.delim(inFile,sep="\t",h=F,as.is=T)[,1]

ppos <- gregexpr("%", dat)
trainCt <- sapply(1:length(ppos), function(k) { 
		no_train <- substr(dat[k],ppos[[k]][1]-2,ppos[[k]][1]-1);
		yes_train<- substr(dat[k],ppos[[k]][2]-2,ppos[[k]][2]-1);
		c(no_train,yes_train)
})
trainCt <- t(trainCt)
class(trainCt) <- "numeric"
colnames(trainCt) <- c("NO","YES")
pdf(sprintf("%s/train.pdf", inDir))
tryCatch({
	par(mfrow=c(1,2))
	boxplot(trainCt,main="% Train"); 
	boxplot(trainCt[,1]-trainCt[,2],main="Diff in No-Yes %")
},error=function(ex){
	print(ex)
}, finally={
	dev.off()
})

