#' Using GMT files, generate enrichment maps and apply Auto annotate app to them

#' @param gmtFile (char) file path to GMT file (generated by writeEMap_file()).
#' NOTE: This needs to be the absolute path name
#' @param nodeAttrFile (list) file path to nodeAttr.txt file (generated by 
#' writeEMap_file()) 
#' @examples
#' plotEmap(gmt_file, node_attrFile, netName="HighRisk")
#' @import r2cytoscape
#' @import httr
#' @importFrom RJSONIO fromJSON
#' @export
plotEmap <- function(gmtFile, nodeAttrFile, netName="generic",
	minScore=1,maxScore=10){

  port.number = 1234
  base.url = paste("http://localhost:", toString(port.number), "/v1", sep="")

  version.url = paste(base.url, "version", sep="/")
  cytoscape.open = TRUE

  tryCatch(expr = { GET(version.url)},
           error = function(e) { return (cytoscape.open = FALSE)},
           finally =function(r){ return(cytoscape.open = TRUE)})

  if(!cytoscape.open){
    #try and launch cytoscape
   print("Cytoscape is not open.  Please launch cytoscape.")
  } else{
    cytoscape.version =  GET(version.url)
    cy.version = RJSONIO::fromJSON(rawToChar(cytoscape.version$content))
    print(cy.version)
  }

  #######################################
  #create EM using given parameters
  #######################################
  #enrichment map command will return the suid of newly created network.
  #Run comman directly in R
  enrichmentmap.url <- paste(base.url, 
			"commands","enrichmentmap","build", sep="/")
  em_params <- list(analysisType = "generic",
			gmtFile = gmtFile,pvalue=1, qvalue=1) 
#			pvalue= p_value_cutoff,qvalue = q_value_cutoff)
  response <- GET(url=enrichmentmap.url, query=em_params)

  #rename network (r2cytoscape function)
  response <- renameNetwork(netName, network = character(0))

  #annotate the network using AutoAnnotate app
  aa_command <- paste("autoannotate annotate-clusterBoosted clusterAlgorithm=MCL maxWords=3
    network=",netName, sep=" ")
  #enrichment map command will return the suid of newly created network.
  response <- commandRun(aa_command)

  table_command <- sprintf("table import file file=%s keyColumnIndex=1
    firstRowAsColumnNames=true startLoadRow=1 TargetNetworkList=%s WhereImportTable=To%%20selected%%20networks%%20only", 
		nodeAttrFile,netName)
cat("about to import table:\n")
  response <- commandRun(table_command)

	#apply style
  all_unique_scores_int <- sort(unique(read.delim(nodeAttrFile)[,2]))
  all_unique_scores <- unlist(lapply(all_unique_scores_int, toString))
  styleName <- "EMapStyle"
  res	<- httr::GET(sprintf("%s/styles",base.url))
  curStyles <- gsub("\\\"","",rawToChar(res$content))
  curStyles <- unlist(strsplit(curStyles,","))

  if (any(grep("EMapStyle",curStyles))) {
  	cat("style exists not creating\n")
  } else {
  	cat("Creating style\n")

	# define colourmap
	scoreVals <- minScore:maxScore
  colfunc <- colorRampPalette(c("yellow", "red"))
  gradient_cols <- colfunc(length(scoreVals))
  style_cols <- colfunc(length(scoreVals)) #gradient_cols[scoreVals[1:length(scoreVals)]]

  style_mapping <- mapVisualProperty(
			visual.prop='node fill color',
			table.column='maxScore',
			mapping.type='d',
			as.character(scoreVals),style_cols,
			network=netName)
 	defaults <- list("NODE_SHAPE"="ellipse",
  			"NODE_SIZE"=30,
  			"EDGE_TRANSPARENCY"=120,
  			"NODE_TRANSPARENCY"=120)
 	sty <- r2cytoscape::createStyle(styleName,
  		defaults=defaults,
  		mappings=list(style_mapping))
  }
  network.suid <- getNetworkSuid()
  # apply style
  apply.style.url <- sprintf("%s/apply/styles/%s/%s",
  	base.url,styleName,network.suid)
  response <- httr::GET(apply.style.url)

	# final layout and redraw
	cat("Final layout and redraw")
	layout_command <- "layout attributes-layout NodeAttribute=__mclCLuster"
    response <- commandRun(layout_command)

    redraw_command <- sprintf("autoannotate redraw network=%s", 
			network.suid)
    response <- commandRun(redraw_command)

}

