#' Wrapper to plot all predictor results
#' 
#' @details only works for binary classification. Assumes the output directory
#' structure generated by running buildPredictor()
#' @param pheno (data.frame) sample metadata. Must have ID and STATUS column
#' @param inDir (char) main directory with results from nested CV run
#' @param outDir (char) directory to store plots and results
#' @param fsCutoff (integer) net must score >= this in CV score cutoff to be
#' called feature-selected
#' @param fsPctPass (numeric from 0 to 1) fraction of splits for which net 
#' must score >= fsCutoff to be called feature-selected
#' @param pathwaySet (list) set of grouped units eligible for EnrichmentMap view
#' If set to NULL, no EnrichmentMap plotted. If provided, must be limited to 
#' the units measured in the dataset. For example, pathway definitions should
#' contain only the genes measured in the input data, and not all genes.
#' @param eMap_colorScheme (char) color scheme for node fills in the Enrichment
#' map. See plotEmap::colorScheme()
#' @param eMap_min (int) min feature score to include in enrichment map
#' @param eMap_max (int) max feature score to include in enrichment map
#' @param setName (char) name of analysis. Used in plot titles
#' @return (list) output from all individual result scripts called.
#' 1) predPerf: output of plotPerf()
#' 2) featScores:
#' 3) featSelNet: (list) keys are classes, values are vectors of feature-
#' selected nets
#' 4) Emap_input: (list) keys are classes, values are output of 
#' writeEMapInput_many(). Only if pathwaySet is provided. 
#' 5) EMap_pngFiles: (list) keys are classes, values are path to png files
#' generated by plotting the EnrichmentMap. Output of plotEMap()
#' 6) PSN: Output of plotIntegratedPSN()
#' @export
plotAllResults <- function(pheno, inDir,outDir,fsCutoff=10L,fsPctPass=0.7,
	pathwaySet=NULL, eMap_colorScheme="cont_heatmap",
	eMap_min=1,eMap_max=10,setName="predictor") {

predClasses <- unique(pheno$STATUS)
cat("* Plotting average and detailed performance\n")


if (file.exists(outDir)) {
	unlink(outDir,recursive=TRUE)
}
dir.create(outDir)

# performance
postscript(sprintf("%s/perf.eps", outDir),height=11,width=6)
tryCatch({
	predPerf <- plotPerf(inDir, predClasses=predClasses)
},error=function(ex) {
	print(ex)
},finally={
	dev.off()
})

# compute feature scores
featScores <- getFeatureScores(inDir,predClasses=predClasses)

dir.create(sprintf("%s/featScores",outDir))
featSelNet <- sapply(names(featScores), function(nm) {
	x <- featScores[[nm]]
	write.table(x,file=sprintf("%s/featScores/%s_featScores.txt",outDir,nm),
		sep="\t",row=TRUE,col=TRUE,quote=F)
	y <- callFeatSel(x, fsCutoff=fsCutoff, fsPctPass=fsPctPass)
	write.table(y,file=sprintf("%s/featScores/%s_FeatSel_cutoff%i_pct%1.2f.txt",	
		outDir,nm,fsCutoff,fsPctPass),sep="\t",col=F,row=F,quote=F)
	y
})


cat("* Generating overall patient similarity view\n")
dir.create(sprintf("%s/PSN",outDir))
netInfo <- plotIntegratedPSN(pheno=pheno,baseDir=sprintf("%s/rng1",inDir),
	netNames=featSelNet,outDir=sprintf("%s/PSN",outDir),setName=setName)


if (!is.null(pathwaySet)) {
	dir.create(sprintf("%s/EMap",outDir))

	cat("* pathwaySet provided; generating EnrichmentMaps\n")
	netInfo <- read.delim(sprintf("%s/inputNets.txt",inDir),
		sep="\t",h=FALSE,as.is=TRUE)
	EMap_input <- writeEMapInput_many(featScores,pathwaySet,
      netInfo,outDir=sprintf("%s/EMap",outDir),
			minScore=eMap_min,maxScore=eMap_max)

	# generate enrichmentmaps
	pngFiles <- list()
	for (curGroup in names(EMap_input)[1:2]) {
		pngFiles[[curGroup]] <- plotEmap(gmtFile=EMap_input[[curGroup]][1], 
	       nodeAttrFile=EMap_input[[curGroup]][2],
	       netName=curGroup,outDir=sprintf("%s/EMap",outDir),
					colorScheme=eMap_colorScheme,
					minScore=eMap_min,maxScore=eMap_max)
	}
}


out <- list()
out[["predPerf"]] <- predPerf
out[["featScores"]] <- featScores
out[["featSelNet"]] <- featSelNet
if (!is.null(pathwaySet)) {
	out[["Emap_input"]] <- EMap_input
	out[["EMap_pngFiles"]] <- pngFiles
}
out[["PSN"]] <- netInfo

return(out)
}
