#' Wrapper to plot all predictor results
#' 
#' @details only works for binary classification. Assumes the output directory
#' structure generated by running buildPredictor()
#' @param pheno (data.frame) sample metadata. Must have ID and STATUS column
#' @param inDir (char) main directory with results from nested CV run
#' @param outDir (char) directory to store plots and results
#' @param fsCutoff (integer) net must score >= this in CV score cutoff to be
#' called feature-selected
#' @param fsPctPass (numeric from 0 to 1) fraction of splits for which net 
#' must score >= fsCutoff to be called feature-selected
#' @param pathwaySet (list) set of grouped units eligible for EnrichmentMap view
#' If set to NULL, no EnrichmentMap plotted. If provided, must be limited to 
#' the units measured in the dataset. For example, pathway definitions should
#' contain only the genes measured in the input data, and not all genes.
#' @param eMap_colorScheme (char) color scheme for node fills in the Enrichment
#' map. See plotEmap::colorScheme()
#' @param eMap_min (int) min feature score to include in enrichment map
#' @param eMap_max (int) max feature score to include in enrichment map
#' @param setName (char) name of analysis. Used in plot titles
#' @param plotNetworks_flag (logical) if TRUE, plots EnrichmentMap & integrated
#' PSN in Cytoscape. 
#' Set to FALSE if running on a machine where Cytoscape is not installed.
#' @return (list) output from all individual result scripts called.
#' 1) predPerf: output of plotPerf()
#' 2) featScores:
#' 3) featSelNet: (list) keys are classes, values are vectors of feature-
#' selected nets
#' 4) Emap_input: (list) keys are classes, values are output of 
#' writeEMapInput_many(). Only if pathwaySet is provided. 
#' 5) EMap_pngFiles: (list) keys are classes, values are path to png files
#' generated by plotting the EnrichmentMap. Output of plotEMap()
#' 6) PSN: Output of plotIntegratedPSN()
#' @export
#' @examples
#' require(netDx.examples)
#' data(KIRC_pheno)
#' 
#' pathFile <- sprintf("%s/extdata/Human_160124_AllPathways.gmt",
#'            path.package("netDx.examples"))
#' pathwayList <- readPathways(pathFile)
#' 
#' xpr_genes <- sprintf("%s/extdata/EMap_input/genenames.txt",
#'       path.package("netDx.examples"))
#' xpr_genes <- read.delim(xpr_genes,h=FALSE,as.is=TRUE)[,1]
#' 
#' pathwayList <- lapply(pathwayList, function(x) x[which(x %in% xpr_genes)])
#' 
#' inDir <- sprintf("%s/extdata/KIRC_output",
#'    path.package("netDx.examples"))
#' 
#' all_rngs <- list.dirs(inDir, recursive = FALSE)
#' out <- plotAllResults(KIRC_pheno, inDir,outDir=sprintf("%s/plots",getwd()),
#'            fsCutoff=10,fsPctPass=0.7,pathwaySet=pathwayList,
#'			  plotNetworks_flag=FALSE)
 plotAllResults <- function(pheno, inDir,outDir=tempdir(),
	fsCutoff=10L,fsPctPass=0.7,
	pathwaySet=NULL, eMap_colorScheme="cont_heatmap",
	eMap_min=1,eMap_max=10,setName="predictor",plotNetworks_flag=FALSE) {

predClasses <- unique(pheno$STATUS)
message("* Plotting average and detailed performance\n")


if (file.exists(outDir)) {
	unlink(outDir,recursive=TRUE)
}
dir.create(outDir)

# performance
#postscript(sprintf("%s/perf.eps", outDir),height=11,width=6)
#tryCatch({
	predPerf <- plotPerf(inDir, predClasses=predClasses)
#},error=function(ex) {
#	print(ex)
#},finally={
	#dev.off()
#})

# compute feature scores
featScores <- getFeatureScores(inDir,predClasses=predClasses)

dir.create(sprintf("%s/featScores",outDir))
featSelNet <- sapply(names(featScores), function(nm) {
	x <- featScores[[nm]]
	y <- callFeatSel(x, fsCutoff=fsCutoff, fsPctPass=fsPctPass)
	y
})

message("* Generating overall patient similarity view\n")
dir.create(sprintf("%s/PSN",outDir))
netInfo <- plotIntegratedPSN(pheno=pheno,baseDir=sprintf("%s/rng1",inDir),
	netNames=featSelNet,outDir=sprintf("%s/PSN",outDir),setName=setName,
	runCytoscape=plotNetworks_flag)

if (!is.null(pathwaySet)) {
	dir.create(sprintf("%s/EMap",outDir))

	message("* pathwaySet provided; generating EnrichmentMaps\n")
	netInfo <- read.delim(sprintf("%s/inputNets.txt",inDir),
		sep="\t",h=FALSE,as.is=TRUE)
	EMap_input <- writeEMapInput_many(featScores,pathwaySet,
      netInfo,outDir=sprintf("%s/EMap",outDir),
			minScore=eMap_min,maxScore=eMap_max)

	# generate enrichmentmaps
	pngFiles <- list()
	if (plotNetworks_flag) {
	for (curGroup in names(EMap_input)[1:2]) {
		pngFiles[[curGroup]] <- plotEmap(
									gmtFile=EMap_input[[curGroup]][1], 
	       							nodeAttrFile=EMap_input[[curGroup]][2],
	       							netName=curGroup,
									colorScheme=eMap_colorScheme,
									minScore=eMap_min,maxScore=eMap_max)
		}	
	}
}

out <- list()
out[["predPerf"]] <- predPerf
out[["featScores"]] <- featScores
out[["featSelNet"]] <- featSelNet
if (!is.null(pathwaySet)) {
	out[["Emap_input"]] <- EMap_input
	out[["EMap_pngFiles"]] <- pngFiles
}
out[["PSN"]] <- netInfo

return(out)
}
