name: Docker Build

on:
  push:
    branches: [ master ]

jobs: 
  build: 

    runs-on: ubuntu-latest
    
    steps: 
    - uses: actions/checkout@v2
      name: Check out code

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build and push Docker image
      with:
        image: realpailab/netdx 
        registry: docker.io
        addLatest: 'true'
        addTimestamp: 'true'        
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}